In [1]:
# Q1. Create a NumPy array arr of integers from 0 to 5 and print its data type.
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5])
print(arr.dtype)


int32


In [2]:
# Q2. Given a NumPy array arr, check if its data type is float64.
arr = np.array([1.0, 2.0, 3.0])
print(arr.dtype == np.float64)


True


In [3]:
# Q3. Create a NumPy array arr with a data type of complex128 containing three complex numbers.
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print(arr)


[1.+2.j 3.+4.j 5.+6.j]


In [4]:
# Q4. Convert an existing NumPy array arr of integers to float32 data type.
arr = np.array([1, 2, 3, 4, 5])
arr_float = arr.astype(np.float32)
print(arr_float)


[1. 2. 3. 4. 5.]


In [5]:
# Q5. Given a NumPy array arr with float64 data type, convert it to float32 to reduce decimal precision.
arr = np.array([1.123456789, 2.987654321], dtype=np.float64)
arr_low_precision = arr.astype(np.float32)
print(arr_low_precision)


[1.1234568 2.9876542]


In [6]:
# Q6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(array_attributes(arr))


((2, 3), 6, dtype('int32'))


In [7]:
# Q7. Create a function array_dimension that returns the dimensionality of a NumPy array.
def array_dimension(arr):
    return arr.ndim

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(array_dimension(arr))


2


In [8]:
# Q8. Design a function item_size_info that returns the item size and total size in bytes of a NumPy array.
def item_size_info(arr):
    return arr.itemsize, arr.nbytes

arr = np.array([1, 2, 3], dtype=np.int32)
print(item_size_info(arr))


(4, 12)


In [9]:
# Q9. Create a function array_strides that returns the strides of the given NumPy array.
def array_strides(arr):
    return arr.strides

arr = np.array([[1, 2], [3, 4]])
print(array_strides(arr))


(8, 4)


In [10]:
# Q10. Design a function shape_stride_relationship that returns the shape and strides of the given array.
def shape_stride_relationship(arr):
    return arr.shape, arr.strides

arr = np.array([[1, 2], [3, 4]])
print(shape_stride_relationship(arr))


((2, 2), (8, 4))


In [11]:
# Q11. Create a function create_zeros_array(n) to return a NumPy array of zeros with n elements.
import numpy as np

def create_zeros_array(n):
    return np.zeros(n)

print(create_zeros_array(5))


[0. 0. 0. 0. 0.]


In [12]:
# Q12. Write a function create_ones_matrix(rows, cols) to create a 2D array filled with ones.
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

print(create_ones_matrix(3, 4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
# Q13. Write a function generate_range_array(start, stop, step) to create a ranged NumPy array.
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

print(generate_range_array(1, 10, 2))


[1 3 5 7 9]


In [14]:
# Q14. Design a function generate_linear_space(start, stop, num) for equally spaced values.
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

print(generate_linear_space(0, 1, 5))


[0.   0.25 0.5  0.75 1.  ]


In [15]:
# Q15. Create a function create_identity_matrix(n) using numpy.eye.
def create_identity_matrix(n):
    return np.eye(n)

print(create_identity_matrix(4))


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
# Q16. Write a function that converts a Python list into a NumPy array.
def list_to_array(lst):
    return np.array(lst)

print(list_to_array([1, 2, 3, 4]))


[1 2 3 4]


In [17]:
# Q17. Create a NumPy array and use numpy.view() to create a new view with the same data.
arr = np.array([10, 20, 30, 40])
view_arr = arr.view()
print(view_arr)


[10 20 30 40]


In [18]:
# Q18. Write a function to concatenate two NumPy arrays along a specified axis.
def concatenate_arrays(arr1, arr2, axis):
    return np.concatenate((arr1, arr2), axis=axis)

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(concatenate_arrays(a, b, axis=0))


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [19]:
# Q19. Concatenate two arrays with different shapes horizontally using numpy.concatenate.
a = np.array([[1], [2]])
b = np.array([[3, 4], [5, 6]])
a_broadcasted = np.concatenate((a, b), axis=1)
print(a_broadcasted)


[[1 3 4]
 [2 5 6]]


In [20]:
# Q20. Vertically stack multiple arrays from a list using numpy.vstack.
arrays = [np.array([1, 2]), np.array([3, 4]), np.array([5, 6])]
stacked = np.vstack(arrays)
print(stacked)

[[1 2]
 [3 4]
 [5 6]]


In [21]:
# Q21. Write a function to generate an array of integers within a specified range (inclusive) with a step.
def generate_inclusive_range(start, stop, step):
    return np.arange(start, stop + 1, step)

print(generate_inclusive_range(1, 10, 2))


[1 3 5 7 9]


In [22]:
# Q22. Generate 10 equally spaced values between 0 and 1 using NumPy.
arr = np.linspace(0, 1, 10)
print(arr)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [23]:
# Q23. Create 5 logarithmically spaced values between 1 and 1000.
arr = np.logspace(0, 3, 5)
print(arr)


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [24]:
# Q24. Create a Pandas DataFrame from a NumPy array with 5 rows and 3 columns of random integers (1–100).
import pandas as pd

data = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(data, columns=['A', 'B', 'C'])
print(df)


    A   B   C
0  33  93  31
1  27  45  56
2  80  17  42
3  89  17  48
4  50  21   7


In [25]:
# Q25. Write a function to replace all negative values in a specific column with zeros using NumPy.
def replace_negatives_with_zero(df, column):
    df[column] = np.where(df[column] < 0, 0, df[column])
    return df

df = pd.DataFrame({'A': [1, -2, 3], 'B': [-4, 5, -6]})
print(replace_negatives_with_zero(df, 'B'))


   A  B
0  1  0
1 -2  5
2  3  0


In [26]:
# Q26. Access the 3rd element from the given NumPy array.
arr = np.array([10, 20, 30, 40, 50])
print(arr[2])


30


In [27]:
# Q27. Retrieve the element at index (1, 2) from a 2D array.
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[1][2])


6


In [28]:
# Q28. Extract elements greater than 5 using boolean indexing.
arr = np.array([1, 6, 3, 7, 2])
print(arr[arr > 5])


[6 7]


In [29]:
# Q29. Slice elements from index 2 to 5 (inclusive) from a NumPy array.
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print(arr[2:6])


[30 40 50 60]


In [30]:
# Q30. Slice the sub-array [[2, 3], [5, 6]] from a 2D array.
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(arr[0:2, 1:3])


[[2 3]
 [5 6]]


In [31]:
# Q31. Extract elements based on indices from a 2D array.
arr = np.array([[10, 20, 30], [40, 50, 60]])
indices = [0, 1]
print(arr[indices])


[[10 20 30]
 [40 50 60]]


In [32]:
# Q32. Filter elements greater than a threshold using boolean indexing.
arr = np.array([1, 4, 7, 2, 9])
threshold = 5
print(arr[arr > threshold])


[7 9]


In [33]:
# Q33. Extract specific elements from a 3D array using separate index arrays.
arr = np.arange(27).reshape(3, 3, 3)
x = [0, 1]
y = [1, 2]
z = [2, 0]
print(arr[x, y, z])


[ 5 15]


In [34]:
# Q34. Return elements satisfying two boolean conditions.
arr = np.array([10, 15, 20, 25, 30])
print(arr[(arr > 15) & (arr < 30)])


[20 25]


In [35]:
# Q35. Extract elements from a 2D array using separate row and column index arrays.
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
row_idx = [0, 1, 2]
col_idx = [2, 1, 0]
print(arr[row_idx, col_idx])


[30 50 70]


In [36]:
# Q36. Add scalar 5 to every element of an array using broadcasting.
arr = np.array([1, 2, 3])
print(arr + 5)


[6 7 8]


In [37]:
# Q37. Multiply each row of a (3, 4) array by corresponding elements of a (1, 3) array.
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
B = np.array([[1], [2], [3]])
print(A * B)

[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]]


In [38]:
# Q38. Add a (1, 4) array to every row of a (4, 3) array using broadcasting.
A = np.ones((4, 3))
B = np.array([[10, 20, 30]])
print(A + B)

[[11. 21. 31.]
 [11. 21. 31.]
 [11. 21. 31.]
 [11. 21. 31.]]


In [39]:
# Q39. Add two arrays of shapes (3, 1) and (1, 3) using broadcasting.
A = np.array([[1], [2], [3]])
B = np.array([[10, 20, 30]])
print(A + B)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [40]:
# Q40. Handle shape incompatibility during multiplication between (2, 3) and (2, 2) arrays.
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4]])

# Cannot multiply directly due to incompatible shapes
try:
    result = A * B
except ValueError as e:
    print("Shape mismatch error:", e)

Shape mismatch error: operands could not be broadcast together with shapes (2,3) (2,2) 


In [41]:
# Q41. Calculate column-wise mean of a 2D array.
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.mean(arr, axis=0))


[2.5 3.5 4.5]


In [42]:
# Q42. Find maximum value in each row.
arr = np.array([[1, 5, 3], [7, 2, 6]])
print(np.max(arr, axis=1))


[5 7]


In [43]:
# Q43. Find indices of maximum values in each column.
arr = np.array([[1, 4, 7], [8, 2, 3]])
print(np.argmax(arr, axis=0))

[1 0 0]


In [44]:
# Q44. Apply a custom function to compute moving sum along rows.
def moving_sum(arr, window=2):
    return np.array([np.convolve(row, np.ones(window, dtype=int), 'valid') for row in arr])

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(moving_sum(arr))

[[ 3  5]
 [ 9 11]]


In [45]:
# Q45. Check if all elements in each column are even.
arr = np.array([[2, 4], [6, 8]])
print(np.all(arr % 2 == 0, axis=0))

[ True  True]


In [46]:
# Q46. Reshape a given array into dimensions m x n.
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [47]:
# Q47. Return a flattened version of a given matrix.
arr = np.array([[1, 2], [3, 4]])
print(arr.flatten())

[1 2 3 4]


In [48]:
# Q48. Concatenate two arrays along a specified axis.
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.concatenate((a, b), axis=0))  # Vertical

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [49]:
# Q49. Split an array into sub-arrays along a specified axis.
arr = np.array([[1, 2, 3], [4, 5, 6]])
split_arr = np.split(arr, 3, axis=1)
print(split_arr)


[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [50]:
# Q50. Insert and delete elements at specified indices from an array.
arr = np.array([10, 20, 30, 40])
arr_inserted = np.insert(arr, 2, 25)  # Insert 25 at index 2
arr_deleted = np.delete(arr, 1)       # Delete element at index 1
print("After insert:", arr_inserted)
print("After delete:", arr_deleted)

After insert: [10 20 25 30 40]
After delete: [10 30 40]


In [51]:
# Q51. Perform element-wise addition between two arrays.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)

[5 7 9]


In [52]:
# Q52. Perform element-wise subtraction: subtract arr2 from arr1.
arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])
print(arr1 - arr2)

[ 9 18 27]


In [53]:
# Q53. Perform element-wise multiplication.
arr1 = np.array([2, 4, 6])
arr2 = np.array([3, 5, 7])
print(arr1 * arr2)

[ 6 20 42]


In [54]:
# Q54. Divide elements of arr1 by arr2 element-wise.
arr1 = np.array([8, 16, 32])
arr2 = np.array([2, 4, 8])
print(arr1 / arr2)

[4. 4. 4.]


In [55]:
# Q55. Perform element-wise exponentiation: arr1 ** arr2.
arr1 = np.array([2, 3, 4])
arr2 = np.array([1, 2, 3])
print(arr1 ** arr2)

[ 2  9 64]


In [56]:
# Q56. Count occurrences of a substring in a string array.
str_arr = np.array(['apple pie', 'pineapple', 'grape apple'])
count = np.char.count(str_arr, 'apple')
print(count)

[1 1 1]


In [57]:
# Q57. Extract uppercase characters from a string array.
str_arr = np.array(['Hello World', 'Python NUMPY', 'ML Rocks'])
def extract_upper(s):
    return ''.join([c for c in s if c.isupper()])
print(np.vectorize(extract_upper)(str_arr))

['HW' 'PNUMPY' 'MLR']


In [58]:
# Q58. Replace substring occurrences with another string in a string array.
str_arr = np.array(['I like cats', 'cats are cute', 'no cats here'])
print(np.char.replace(str_arr, 'cats', 'dogs'))

['I like dogs' 'dogs are cute' 'no dogs here']


In [59]:
# Q59. Concatenate strings in a NumPy array element-wise.
arr1 = np.array(['Hello', 'Good'])
arr2 = np.array(['World', 'Morning'])
print(np.char.add(arr1, arr2))

['HelloWorld' 'GoodMorning']


In [60]:
# Q59. Concatenate strings in a NumPy array element-wise.
arr1 = np.array(['Hello', 'Good'])
arr2 = np.array(['World', 'Morning'])
print(np.char.add(arr1, arr2))

['HelloWorld' 'GoodMorning']


In [61]:
# Q61. Generate 100 random integers (1–1000) and compute mean, median, variance, and std deviation.
arr = np.random.randint(1, 1001, size=100)
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Variance:", np.var(arr))
print("Standard Deviation:", np.std(arr))

Mean: 453.05
Median: 380.5
Variance: 105148.7875
Standard Deviation: 324.26653774325837


In [62]:
# Q62. Generate 50 random numbers (1–100) and compute the 25th and 75th percentiles.
arr = np.random.randint(1, 101, size=50)
print("25th percentile:", np.percentile(arr, 25))
print("75th percentile:", np.percentile(arr, 75))

25th percentile: 34.75
75th percentile: 60.75


In [63]:
# Q63. Compute correlation coefficient between two arrays using np.corrcoef.
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])
print(np.corrcoef(arr1, arr2))

[[ 1. -1.]
 [-1.  1.]]


In [64]:
# Q64. Perform matrix multiplication using np.dot.
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.dot(a, b))

[[19 22]
 [43 50]]


In [65]:
# Q65. Compute the 10th, 50th, and 90th percentiles and quartiles for an array of 50 integers.
arr = np.random.randint(1, 101, size=50)
print("10th percentile:", np.percentile(arr, 10))
print("50th percentile (median):", np.percentile(arr, 50))
print("90th percentile:", np.percentile(arr, 90))
print("1st quartile (Q1):", np.percentile(arr, 25))
print("3rd quartile (Q3):", np.percentile(arr, 75))

10th percentile: 8.600000000000001
50th percentile (median): 40.0
90th percentile: 88.1
1st quartile (Q1): 22.0
3rd quartile (Q3): 65.75


In [66]:
# Q66. Find index of a specific element in an array.
arr = np.array([10, 20, 30, 40, 50])
index = np.where(arr == 30)
print(index[0][0])

2


In [67]:
# Q67. Sort a random array in ascending order.
arr = np.random.randint(1, 100, size=10)
sorted_arr = np.sort(arr)
print(sorted_arr)

[ 9 24 24 25 32 41 46 52 74 95]


In [68]:
# Q68. Filter elements greater than 20.
arr = np.array([5, 25, 15, 35, 10])
print(arr[arr > 20])

[25 35]


In [69]:
# Q69. Filter elements divisible by 3.
arr = np.array([3, 6, 10, 12, 15, 17])
print(arr[arr % 3 == 0])

[ 3  6 12 15]


In [70]:
# Q70. Filter elements between 20 and 40 (inclusive).
arr = np.array([10, 20, 25, 30, 40, 50])
print(arr[(arr >= 20) & (arr <= 40)])

[20 25 30 40]


In [71]:
# Q71. Check byte order of a NumPy array using dtype.byteorder.
arr = np.array([1, 2, 3])
print(arr.dtype.byteorder)

=


In [72]:
# Q72. Perform in-place byte swapping using byteswap().
arr = np.array([1, 256, 65536], dtype=np.int32)
arr.byteswap(inplace=True)
print(arr)

[16777216    65536      256]
